chore : Uploade SQL homework
Fullstack-Alfanar/Aiman-React-Homeworks pull request #10
Opened 2022-08-26 13:29 UTC by aimanzi

2022-08-26 13:34 UTC, EliasSalom requested changes
please check my comment

2022-08-26 13:34 UTC, EliasSalom commented on SQL/booktable.sql
> +Pages Number numeric
you need to choose between the number or numeric!!

2022-08-27 17:29 UTC, aimanzi commented on SQL/booktable.sql
> +Pages Number numeric
problem solved

2022-08-29 06:31 UTC, EliasSalom approved these changes
LGTM

2022-08-29 06:31 UTC, EliasSalom commented
there is some conflicts that must be resolved

2022-08-29 11:45 UTC, closed without merging

2022-08-29 11:49 UTC, EliasSalom commented
**don't close any pull request without comment, this is not allowed**